# Generated by Django 4.1.2 on 2022-10-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Number')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salary')),
                ('department', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentname', to='Employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('number', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.project')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(through='Employee.WorkOn', to='Employee.project'),
        ),
    ]
